version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=780155373008.dkr.ecr.us-east-1.amazonaws.com/animl/mal-user-crawler
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t mal-user-crawler .
      - docker tag mal-user-crawler:latest 780155373008.dkr.ecr.us-east-1.amazonaws.com/animl/mal-user-crawler:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 780155373008.dkr.ecr.us-east-1.amazonaws.com/animl/mal-user-crawler:latest
      - echo Writing image definitions file...
      - printf '[{"name":"mal-user-crawler","imageUri":"%s"}]' 780155373008.dkr.ecr.us-east-1.amazonaws.com/animl/mal-user-crawler:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json